/* eslint-disable perfectionist/sort-objects */

export type SolvedVisualization = {
  href: string;
  tags: Tag[];
  title: string;
  description: string;
};

export type Tag = 'Algorithm' | 'Iterative';
export type Days = [never, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];
export type Year = Partial<{
  [K in Exclude<keyof Days, '0' | keyof []>]: SolvedVisualization;
}>;

// This file is auto-generated by the build process
// Do not edit manually - changes will be overwritten

export const SOLUTIONS: Record<number, Year> = {
  2024: {
    10: {
      description: 'Traverse from each trailhead through increasing heights, counting unique and all paths.',
      href: '/2024/10',
      tags: [
        'Algorithm'
      ],
      title: '10th'
    },
    12: {
      description: 'Implementation of a <em>flood fill</em> algorithm to dectect consequent areas.',
      href: '/2024/12',
      tags: [
        'Algorithm'
      ],
      title: '12th'
    },
    15: {
      description: "Analyze the robot's actions while accounting for obstacles and blocked movements on a map.",
      href: '/2024/15',
      tags: [
        'Algorithm'
      ],
      title: '15th'
    }
  },
  2023: {
    10: {
      description: "Trace a continuous loop through a grid of interconnected pipe segments, identifying the loop's path and determining distances and enclosed areas.",
      href: '/2023/10',
      tags: [
        'Algorithm'
      ],
      title: '10th'
    }
  },
  2022: {
    5: {
      description: 'The 5th anniversary of the Svelte framework',
      href: '/2022/5',
      tags: [
        'Algorithm',
        'Iterative'
      ],
      title: '5th'
    }
  }
};
