
import type { Year } from '$lib/utils';

// This file is auto-generated by the build process
// Do not edit manually - changes will be overwritten

export const SOLUTIONS: Record<number, Year> = {
  2022: {
    5: {
      description: 'The 5th anniversary of the Svelte framework',
      href: '/2022/5',
      tags: [
        'Algorithm',
        'Iterative'
      ],
      title: '5th'
    }
  },
  2023: {
    10: {
      description: "Trace a continuous loop through a grid of interconnected pipe segments, identifying the loop's path and determining distances and enclosed areas.",
      href: '/2023/10',
      tags: [
        'Algorithm'
      ],
      title: '10th'
    }
  },
  2024: {
    10: {
      description: 'Traverse from each trailhead through increasing heights, counting unique and all paths.',
      href: '/2024/10',
      tags: [
        'Algorithm'
      ],
      title: '10th'
    },
    12: {
      description: 'Implementation of a <em>flood fill</em> algorithm to dectect consequent areas.',
      href: '/2024/12',
      tags: [
        'Algorithm'
      ],
      title: '12th'
    },
    15: {
      description: "Analyze the robot's actions while accounting for obstacles and blocked movements on a map.",
      href: '/2024/15',
      tags: [
        'Algorithm'
      ],
      title: '15th'
    }
  }
};
